### ISSUE TITLE
Using ember.js...

### ISSUE THREAD

**Issue by karelvh** [arnvanhoutte/Drivr#1]
see title.

**Comment by arnvanhoutte** [comment]
Yeah I know...

**Comment by arnvanhoutte** [comment]
But Xamarin tho!! :D

**Comment by karelvh** [comment]
no. pliz kill project. pliz.

**Comment by arnvanhoutte** [comment]
![](http://cdn.quotesgram.com/small/44/82/67139225-46070194.jpg)

**Comment by arnvanhoutte** [comment]
Feel free to help tho!

**Comment by jonatanmichiels** [comment]
@karelvh Any reasons why?

**Comment by karelvh** [comment]
@jonatanmichiels it's ember

**Comment by jonatanmichiels** [comment]
Ember is removed from the project

**Comment by justijndepover** [comment]
lol
